[package]
name = "dororong"
version = "0.1.3"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
crossterm = "0.29.0"
lazy_static = "1.5.0"
tokio = { version = "1.47.1", features = ["full"] }
